# Generated by Django 3.2.13 on 2022-11-29 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('broker_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('share', models.FloatField(null=True)),
                ('investors', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='broker_app.investors')),
            ],
        ),
        migrations.CreateModel(
            name='profit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('projects', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='broker_app.projects')),
            ],
        ),
    ]
