# Generated by Django 3.2.13 on 2022-12-03 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broker_app', '0009_profit_tbl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='date_added',
            field=models.DateField(null=True),
        ),
    ]
