# Generated by Django 3.2.13 on 2022-12-05 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broker_app', '0011_payments_tbl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profit',
            name='projects',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='investors',
        ),
        migrations.AddField(
            model_name='projects',
            name='investor_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='payments',
        ),
        migrations.DeleteModel(
            name='profit',
        ),
    ]
