# Generated by Django 3.2.13 on 2022-12-05 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broker_app', '0012_auto_20221205_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='share',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
