# Generated by Django 3.2.13 on 2022-12-06 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('broker_app', '0014_auto_20221206_1538'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='investor_name',
        ),
        migrations.AddField(
            model_name='projects',
            name='investor_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='broker_app.investors'),
        ),
    ]
