# Generated by Django 3.2.13 on 2022-12-07 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broker_app', '0016_alter_projects_share'),
    ]

    operations = [
        migrations.CreateModel(
            name='statements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opening_balance', models.FloatField(null=True)),
                ('credits', models.FloatField(null=True)),
                ('debits', models.FloatField(null=True)),
                ('date', models.DateField()),
                ('particular', models.CharField(max_length=100, null=True)),
                ('balance', models.FloatField(null=True)),
            ],
        ),
    ]
