# Generated by Django 3.2.13 on 2022-12-07 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('broker_app', '0017_statements'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='statements',
            new_name='statements_tbl',
        ),
    ]
