# Generated by Django 3.2.13 on 2022-12-07 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('broker_app', '0019_statements_tbl_investor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statements_tbl',
            name='investor',
        ),
        migrations.AddField(
            model_name='statements_tbl',
            name='projects',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='broker_app.projects'),
        ),
    ]
