# Generated by Django 3.2.13 on 2022-12-07 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('broker_app', '0020_auto_20221207_1152'),
    ]

    operations = [
        migrations.DeleteModel(
            name='statements_tbl',
        ),
    ]
