# Generated by Django 3.2.13 on 2022-12-08 04:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('broker_app', '0021_delete_statements_tbl'),
    ]

    operations = [
        migrations.CreateModel(
            name='credits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('description', models.CharField(max_length=25, null=True)),
                ('amount', models.FloatField(null=True)),
                ('profit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='broker_app.profit_tbl')),
            ],
        ),
    ]
