# Generated by Django 3.2.13 on 2022-12-08 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broker_app', '0022_credits'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='credits',
            name='profit',
        ),
        migrations.AddField(
            model_name='credits',
            name='investor',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
