# Generated by Django 3.2.13 on 2022-12-08 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broker_app', '0023_auto_20221208_0937'),
    ]

    operations = [
        migrations.CreateModel(
            name='multiple_projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projects', models.ManyToManyField(to='broker_app.projects')),
            ],
        ),
    ]
