# Generated by Django 3.2.13 on 2022-12-08 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('broker_app', '0024_multiple_projects'),
    ]

    operations = [
        migrations.DeleteModel(
            name='multiple_projects',
        ),
    ]
