# Generated by Django 3.2.13 on 2022-12-08 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('broker_app', '0026_alter_profit_tbl_projects'),
    ]

    operations = [
        migrations.DeleteModel(
            name='credits',
        ),
    ]
