# Generated by Django 3.2.13 on 2022-12-08 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('broker_app', '0027_delete_credits'),
    ]

    operations = [
        migrations.CreateModel(
            name='accounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payments', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='broker_app.payments_tbl')),
                ('profits', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='broker_app.profit_tbl')),
            ],
        ),
    ]
