# Generated by Django 3.2.13 on 2022-12-08 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('broker_app', '0028_accounts'),
    ]

    operations = [
        migrations.DeleteModel(
            name='accounts',
        ),
    ]
