# Generated by Django 3.2.13 on 2022-12-09 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broker_app', '0029_delete_accounts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments_tbl',
            name='investor',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
